### ISSUE TITLE
RealTrouble U8 not listed in BOM (Ironwood Socket for ASIC), flash chip, and C27 Q.

### ISSUE THREAD

**Issue by cmcjames** [bespoke-silicon-group/bsg_motherboards#2]
Hello,

**Question 1-**
We are basing our design on RealTrouble and while socket U8 is shown in the schematic page 2 of 18, bottom right, I do not see it in the Bill of Materials.  Our die and package is based on BSG_332.

What is the Ironwood part number for the socket?
Do we need any special permission from BaseJump to have Ironwood manufacture the socket for us?

**I see this picture for the ASIC pins, a 22x22 array**:
_https://github.com/bespoke-silicon-group/bsg_packaging/blob/master/ucsd_bga_332/pcb/352_bga_pins_top_down_flat.pdf_
and I can’t find the Ironwood socket to match. **I only see this Ironwood SG-BGA676 socket, which is 26x26pins**.
_https://raw.githubusercontent.com/bespoke-silicon-group/bsg_motherboards/master/bsg_trouble/super_trouble_v2/misc_docs/C17099%20Dwg.pdf_

I assume the 26x26 pin socket is not for the 22x22 pin ASIC array.

Question 2-
We need to substitute the flash chip. The original chip is: M25P128-VME6TGB and thank you for recommending to my colleague for the DT board MT25QL128ABA1EW9-0SIT.  The first is obsolete and the second is now out of stock. I’ve asked Micron, but they haven’t returned my request for a replacement part number.
Assuming I require the following characteristics: _NOR-Flash, 128Mb as 16Mx8, SPI interface, 2.7-3.6V, surface mount, in-stock, ROHS, (original F=54MHz, original write cycle time: 15ms, 5ms)_, it seems there aren’t any Micron parts. There are parts from  _Macronix_, I do not know if their parts are fully compatible. We can handle a footprint change at this time, but we are hoping we won’t need to change the gateway FPGA code. The Macronix parts in stock that fit the bill are: MX25L12835FM2I-10G, MX25L12835FMI-10G, MX25L12835FZNI-10G and links to each of those come up in [this digikey search](https://www.digikey.ca/en/products/filter/memory/774?s=N4IgjCBcoGwJxVAYygMwIYBsDOBTANCAPZQDaIALAAxwDMdIAuoQA4AuUIAymwE4CWAOwDmIAL6EwFAEyIQKSBhwFiZEAA4YAVnWzmIdpx4CR4wtIDsMOQqV5CJSOTC0KcKhSasOkbnyGiEiBaFlQ2aFj2qk4grhbxEPqGvsYBZiBwMBDQ8hHKDmpxFjpeBj5%2BJoHmHrThipEqjuTUWVTWSeWppkEAtLI5CnwAro1qWky9tQNQw6MxYGGMYstAA). _Would you recommend any one of those?_

Question 3 (out of curiosity)-
C27 is a 10UF tantalum capacitor in parallel with C37 a 0.1UF capacitor by the serial port’s MAX322EEUP. The MAX322 datasheet requires the 0.1UF capacitor and nothing more.  What is the reason the team decided to include a large tantalum capacitor as well?

Question 4: What is the proper way to acknowledge the BSG group?  (sorry, I don't see a group for this topic!)

**Comment by taylor-bsg** [comment]
Ironwood:

https://github.com/bespoke-silicon-group/bsg_packaging/tree/master/ucsd_bga_332/pcb/for_socket_maker_ironwood
part number is C16459

**Comment by taylor-bsg** [comment]
@gaozihou may be able to answer #2 and #3

#4: "Our system employs the BaseJump Socket 332, BaseJump RealTrouble motherboard, and firmware, designed by the UW Bespoke Silicon Group, available at http://bjump.org."

**Comment by gaozihou** [comment]
Hi @cmcjames,

Q1. More information can be found here: https://github.com/bespoke-silicon-group/bsg_motherboards/blob/master/bsg_trouble/real_trouble/misc_docs/C16459_PCB%20Layout.PDF 

Q2. The real question is "which NOR flash devices can be indirectly programmed by the iMPACT tool through a Spartan-6 device". You could refer to the Xilinx Q&A: https://www.xilinx.com/support/answers/70681.html (also mentioned here: https://github.com/bespoke-silicon-group/basejump_stl/issues/430). From my understanding, Macronix would work but it does not have as much software support (iMPACT tool) as Micron devices. In general I would suggest continue using Micron chips to make flash programming process simpler.

I understand it is hard to find chips in stock due to the global chip shortage.. I found this on digikey which should be a proper replacement: https://www.digikey.com/en/products/detail/micron-technology-inc/N25Q128A13EF840E/13167381

Q3. I guess it is just a conservative design to ensure VDD is clean.

**Comment by cmcjames** [comment]
Thank you very much everyone for your timely response!  It's much appreciated!
I'll have to place our Ironwood and Digikey orders soon. 
Regarding Q2: Macronix got back to me with some replacement parts. They do mention challenges with respect to programming with the Xilinx iMPACT tools and they have provided some suggestions to make things work.  The link provided didn't work for me, but a search on a subset of the part number did, it seems a Digikey marketplace reseller, _Flip Electronics_, has that particular replacement in stock so thank you very much!
